### ISSUE TITLE
Stealth mode mounting 

### ISSUE THREAD

**Issue by Klaceyes** [ValorenWoW/sunstrider-core#13]
**Description:**

Mounting while in stealth as rogue isn't removing the stealth stance

**Current behaviour:**

The stealth mode isn't dissapearing when casting a mount on stealth
Also, we are entering in mount while remaining **_in stealth_**

**Expected behaviour:**

Any action that isn't considered as a direct attack or the use of an item should make the player becoming instantly unstealth

**Steps to reproduce the problem:**

Entering in stealth and casting a mount

**rev. hash/commit:** 

Don't understand bud, need explanation

**Operating system:** 

Windows 10

**Comment by Klaceyes** [comment]
It happened one time, after few try's i wasn't able to reproduce it

I'll add that i was able to start a fight and attack a target while in stealth, it kept like that until the monster reset his initial place and found me, which unstealthed my character

**Comment by woiwoz** [comment]
Is this the server you compiled yourself?

**Comment by kelno** [comment]
Thanks, and I really appreciate you joining a video.

I'm unable to reproduce it with current infos and I can't see any obvious reasons in the code. I'll need a way to reproduce it or other hints.
From what I can see in code the bug is probably already happening at the time the stealth is cast, if you're investigating this bug you should be extra attentive to what's happening at this time rather than when stealth is dropped.

Dev note: 
m_interruptMask is probably faulty here and not updated when stealth is applied.
