### ISSUE TITLE
Double windfury weapon has too low proc chance

### ISSUE THREAD

**Issue by Felipe1348** [ValorenWoW/sunstrider-core#4570]
**Describe the bug**
Using windfury weapon enchant on both hands should have a 36% chance to proc windfury outside the internal cooldown. With the sum of all possible hits that could proc wf, the proc rate should be 20% while dualwielding, even a little more depending on rng.

**Character name**
The name of my character is Bajinazo. I've been testing this for weeks with almost same results and very little variations.

**To Reproduce**
(IMPORTANT: first of all, i used gear with a lot of hit rating and good amount of expertise, and i used gear with haste. Weapons i chose were slow one hands like syphon of the nathrezim and dragonstrike, and fasters weapons like vanyrs. No big variations at all, **still low proc rates between 12-14%**).

1. Imbue your weapons with windfury weapon on both hands.
2. Attack a dummy using white hits for 5, 10, 15, 30 minutes or an hour.
3. Use the addon Recount to make the calculations.
4. Sum all the possible hits that could proc wf, in this case white hits, critical white hits and glancing hits.
5. Divide the total wf procs by 2 (recount counts 1 proc as 2) and multiplicate by 100.
6. The result of step 5 divide it by the sum of all posible hits (step 4).

![10 min](https://user-images.githubusercontent.com/75688182/101687403-328c2100-3a49-11eb-92c0-a9b39c3fb3ea.jpg)
10 minutes: 13.3% proc chance.

![30 min](https://user-images.githubusercontent.com/75688182/101687756-b940fe00-3a49-11eb-8d7d-009f7d5180c0.jpg)
30 minutes: 13.9% proc chance.

![1 h](https://user-images.githubusercontent.com/75688182/101687898-ed1c2380-3a49-11eb-9b42-700a4257ed74.jpg)
1 hour: 14.6% proc chance

I read the same problem on other private server's bug tracker and the problem was fixed.
I even tested the same thing on another private server with the same steps and the results were 20-21% wf proc chances.
(I didnt say the the name of the servers and didnt upload a screenshot of my results, maybe it is against Endless rules i dont know).

**Expected behavior**
> When you dual wield weapons, the chance on each landed attack outside the 3-second cooldown is approximatedly 36%, if and only if both weapons are imbued with Windfury. Originally posted by Disquette on the WoW official forums. Original post is no longer archived by Blizzard. Analysis of the combat log shows that if you sum all hits, the proc rate while DWing is 20%, but that includes hits you make while inside the 3 second cooldown, which cannot actually proc WF. When you remove the ineligible hits the observed proc rate from the eligible hits becomes 36%.

From the "bible" of enhancement shamans: [https://web.archive.org/web/20080811071236/http://elitistjerks.com/f47/t20765-shaman_enhancement/](url)

**Screenshots/videos**
Take this videos for example, they are from retail back in 2007, 2008. You can aprecciate how often wf procs while dualwielding. On Endless there are so many dead times without any proc.
[https://www.youtube.com/watch?v=YhD4yVauDhA](url)
[https://www.youtube.com/watch?v=b3mty6Jm9yQ](url)
[https://www.youtube.com/watch?v=1kuHv539R2A&t=104s](url) yeah, the video is a little speed up.

**Additional context**
I made this mostly because, for months, i have been finding weird the fact that t6 shamans (including me) meta is windfury main hand and flametongue offhand, and for sure its more dps, but thats the point, back in TBC, WF/FT never was superior than WF/WF especially in t6. Windfury only scales better and better trough the game. I wonder why any enhan shaman didn't report this before. Hope you enhan shamans, devs or gms can take a look at this. We all know windfury is our primordial source of damage and i think it need to be fixed or at least revisited, because double windfury weapon damage output is awful.
This post is about dual windfury weapon proc chance, I HOPE other values, like the attack power bonus damage or the priority of the main hand over the off hand to proc wf, are working good.
Thanks for read.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The first thing to consider here is the tests performed and what they're compared to. Testing by just meleeing a dummy and comparing it to a raid environment with buffs, boss debuffs, consumables, bloodlusts is hardly proof that anything's wrong.
Here are some conclusions from talking to Genepool who also plays Enhancement:

> Oke tested some more and looked through some more resources. I think the guy who made the report ran a fairly unrealistic test. In any raid scenario we'd use stormstrike off CD which increases windfury proc rate. On top of that, fairy fire also makes us straight get about 3% more hits which is also going to increase WF procs slightly.  In addition, I dug up this older discussion on WF proc rate which states that:
> "Under a perfect set of circumstance the maximum proc rate for Windfury Weapon is 20ppm, though it is typically around 15 ppm when wielding slow weapons" 
> http://web.archive.org/web/20080811084026/http://elitistjerks.com/f47/t15809-shaman_windfury/#Windfury_Weapon
> 
> And that's about the result I'd expect in a raid environment. Considering kings, ff, haste pots, bloodlust, drums etc. for the proc rate to be anywhere between 12-15ppm. 20ppm is the absolute perfect outcome which would require a swingspeed of 3sec or 1.5sec (or another number that lands a swing exactly every 3 seconds). 60/3=20ppm
> Assuming a 1.5sec swing timer over 60 seconds this would result in 80hits (60/1.5*2(both weapons)) per minute. No misses no dodges. Windfury procced 20 times (maximum amount). Running these number through his calculations it results in 25%. And this is the perfect theoretical outcome with perfect weapon speed and 100% windfury proc rate every second swing. That our results outside of a raid with no specials land between 13-15% seems more than normal. Now assuming 15ppm it would land at about 18.75%. But that's still with perfect swing speed (which nobody has) and no misses or dodges (which also nobody has).
> Hopefully my math isn't totally off though I am not that great with numbers but it should be correct unless I've made a wrong assumption somewhere.

Another simple eye test of trying to tell  whether something is wrong is comparing how much % of total damage do Windfury procs consist of on the server vs retail vs even other private servers.
From doing these comparisons I can say that the difference is at best neglible if it exists at all in most cases in the limited amount of data we have access to.

**Comment by SabreValkyrn** [comment]
>Using windfury weapon enchant on both hands should have a 36% chance to proc windfury outside the internal cooldown.

Doesn't that assume the 3s ICD is *not* shared between MH and OH? https://github.com/SunstriderEmu/BugTracker/issues/1228#issuecomment-490261064

Which was recently fixed: https://github.com/SunstriderEmu/BugTracker/issues/1228#issuecomment-688832403

From [patch 2.1.0 (2007-05-22)](https://wowwiki.fandom.com/wiki/Patch_2.1.0#Shaman) 

>Windfury Weapon: Mixing two different ranks of Windfury Weapon while dual-wielding will no longer increase the number of Windfury Weapon procs.

The 2.1.0 change implemented a 3 second Internal Cooldown (ICD) across all levels of Windfury. Doesn't this mean if your Off-Hand Windfury, regardless of rank, triggers Windfury then your Main Hand WF cannot proc for 3 seconds. A bunch of fancy math aside, it basically means your Windfury did 50% less damage than it could have, and prevents your Main-Hand from triggering Windfury for 3 seconds.

I don't see how WF/WF sharing the same 3s ICD can realistically proc more than the 15-18% Genepool's detailed breakdown covers.

That "enhancement bible" also results in ~1.5s downtime for WF in the party with their twisting macro, so it's not a perfect guide.

In BiS SWP gear on another server, I did extensive WF/WF vs WF/FT testing (copy/paste from previous forum)

>Keep in mind that these might be 50-100DPS different, but that gap will only get larger with raid composition. Battle shout, faerie fire, bloodlust, executioner/mongoose, haste pots, flamecaps, sunder/expose armor, etc will likely all increase the gap between WF/FT and WF/WF.

Methodology:

- no food buffs
- no flasks
- no raid buffs
- cancelaura mongoose/executioner on EarthShock macro
- agi/mana/str totems
- water shield
- armored bossy dummy, from behind
- 30 minute sessions (the length of imbues)
- not using cooldowns like Blood Fury, haste pot, flame caps, or bloodlust
- using StormStrike and EarthShock immediately on cooldown, to keep relic and Ashtongue Talisman of Vision procced
- not rotating flameshock in for simplicity, since this is about weapon imbues
- no fire totems
- Recount hidden, to avoid confirmation bias

Did two runs for WF/FT and WF/WF for more comparison data.

- Hand of the Deceiver (WF5) + Mounting Vengeance (FT): 1059 DPS, 1050 DPS
- Hand of the Deceiver (WF5) + Mounting Vengeance (WF5): 1002 DPS, 993 DPS 
- Hand of the Deceiver (WF5) + Mounting Vengeance (WF4): 990 DPS
- Hand of the Deceiver (WF5) + Mounting Vengeance (RB): 1034 DPS
 
>WF/WF is a lot closer than I expected it to be, but that might be more forgiving because I'm at 105 hit, so the OH doesn't steal MH WF procs as much as it could.

The following do not satisfy meta, but were surprisingly close.

- Hand of the Deceiver (WF5) + Grip of Manaroth (FT): 989 DPS
- Hand of the Deceiver (WF5) + Grip of Manaroth (RB): 1006 DPS
- Swiftsteel Bludgeon (FT) + Grip of Manaroth (FT): 829 DPS
- Swiftsteel Bludgeon (RB) + Grip of Manaroth (RB: 785 DPS
- Torch of the Damned (WF5): 862 DPS

>I could have done more 30 minute runs, but almost 6 hours straight is a bit taxing.

**Comment by Jerrythemagicdog** [comment]
Closing for now then, feel free the write here if you find anything new and we'll reopen.
