### ISSUE TITLE
Frozen shadow weave gear set bonus not proccing heal properly on blizzard *spell*

### ISSUE THREAD

**Issue by TheGreyMouser** [ValorenWoW/sunstrider-core#4597]
**Describe the bug**
 I don't think the set bonus is proccing properly from blizzard on https://www.wowhead.com/item=21871/frozen-shadoweave-robe bonus.  I killed a hellboar with 5k HP using only blizzard and got only 10 HP returned to me. I should have gotten 100hp (aprox) according to the 2% health bonus from frost damage.
**Character name**
Frostyjack

**To Reproduce**
cast blizzard while looking at "what happened to me" in the combat log

**Comment by kelno** [comment]
Two effects here:
- Chance get reduced from 100% to a lower chance divided across all ticks because this is a channeled spell. This looks wrong in this case.
- There is some rounding down happening with some small values like 2% of 325 dmg, like a blizzard tick. This is minor compared to the first effect though.

**Comment by kelno** [comment]
Fixed with next server update
aa9a9244cbc279330fe5f02ab58ec7dbe9c38a2f
