### ISSUE TITLE
bt, mother off tank ported

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4672]
bt, mother, prot paladin off tank got ported for beams

last week prot pal got ported for beams at least a full minute into the fight... mightve been several minutes, but it certainly wasn't the first beam.  

Can probably find a video of it if that would help you figure out why this happened but ...

i posted a similar issue that was closed as invalid... so maybe its not an issue...  
https://github.com/SunstriderEmu/BugTracker/issues/4624

**Comment by mechanicsTBC** [comment]
post a vod

**Comment by Sarlisark** [comment]
Also one thing to be aware of is that, from what I could gather, each tank has to be hit by the cleave of mother at least once every third or fourth cleave (so no dodging/missing/parrying) otherwise the tank does not get the immunity against teleporting, since it is something akin to a "hidden debuff" you get if you are hit by the cleave.
That means an off tank has to make sure that after 3 dodges/misses/parries he gets hits by the next one or he could be targeted for port(e.g. turn around and get hit once in the back)
It is possible that this was not the case for you but for that one would need more information/video hit logs on him to reconstruct what may have happened
