### ISSUE TITLE
BRD Emperor room

### ISSUE THREAD

**Issue by TheGreyMouser** [ValorenWoW/sunstrider-core#4677]
In black rock depth, killed Ironhand Guardian but the door didn't open to access last boss.

**Comment by Sheikthecatman** [comment]
Killing Magmus opens the door to the final boss. Did you kill him to proceed?

**Comment by TheGreyMouser** [comment]
That is my point.. it didn't.  Maybe because we pulled him back to the door from the gnomes?  Flames did not stop when he died either.

________________________________

**Comment by Sheikthecatman** [comment]
I tested killing Magmus and the door opened, however I've changed the check for the door and it might be more consistent now.
I've also made it so the flames stop now when Magmus dies. Fixes applied after next server restart.

Fixed in [309cbc62dc52504234f5ba1ba598650e2d543b67](https://github.com/kelno/sunstrider-scripts/commit/309cbc62dc52504234f5ba1ba598650e2d543b67).
