### ISSUE TITLE
Gray Level mobs gives experience.

### ISSUE THREAD

**Issue by PPGGPilot** [ValorenWoW/sunstrider-core#4690]
**Describe the bug**
Gray Level mobs gives experience if players kill them.

**Character name**
All characters.

**To Reproduce**
I fully saw this problem by playing one of my characters at level 50. Killing mobs at level 40 gives me experience points.
So to reproduce the problem just be level 50 and try to kill various mobs at lvl 40.

**Expected behavior**
Gray Level mobs gives no XP and full reputation. It varies based on your character level. For example: if char level is 50 -> Gray level = Char level - 10 = 40 (50-10=40). So i should get xp for killing mobs at minimum level 41.
Full explanation on the following webpages: 
https://wowwiki-archive.fandom.com/wiki/Formulas:Mob_XP
https://wowwiki-archive.fandom.com/wiki/Mob_difficulty_colors

**Screenshots/videos**
I have no screenshots/videos.

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
The formulas from the wowwiki page that we're using:
```
Char level  1-5:  Gray level = 0 (all mobs give XP)
Char level  6-39: Gray level = Char level - FLOOR(Char level/10) - 5
Char level 40-59: Gray level = Char level - FLOOR(Char level/5) - 1
Char level 60-70: Gray level = Char level - 9 = 51 @ 60, 61 @ 70
```

A level 50 character is in the 40-59 bracket, so with that formula a level 40 creature should still provide experience for a level 50 character (a level 40 Drywallow Daggermaw in this example which is displayed as gray in that case by the client).
Seems like the formula provided is incorrect because in cases like this one we do end up with gray mobs providing experience.

**Comment by PPGGPilot** [comment]
Any chance that will be fixed soon?

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
