### ISSUE TITLE
Seal of vengeance SP scaling is using old values

### ISSUE THREAD

**Issue by westlakem** [ValorenWoW/sunstrider-core#4733]
**Describe the bug**
SoV dot damage should be scaling with 3.4% spell power per stack, not the old values of 2.2%

![image](https://user-images.githubusercontent.com/4505074/109608303-ab09f780-7af7-11eb-982d-e8d97a219e9b.png)

Currently, damage is scaling at 2.2% of spell power
damagePer15 = (150 + (spellDamage * (0.022 * numOfStacks))) * numOfStacks
(150+(107*(0.022*5)))*5 = 808.85
808.85 / 5 (1 tick every 3 seconds for 15 seconds) = 161.77
161.77 * 1.05 (one handed spec) = 169.86

instead of 3.4%
damagePer15 = (150 + (spellDamage * (0.034 * numOfStacks))) * numOfStacks
(150+(107*(0.034*5)))*5 = 840.95
840.95 / 5 (1 tick every 3 seconds for 15 seconds) = 168.19
168.19 * 1.05 (one handed spec) = 176.60

A character with 107 spell damage and 5 points in 1h weapon specialization should be doing about 177 damage per tick, not 170 (and the difference only gets worse with more SP)

**Character name**

**To Reproduce**

1. Auto attack a target dummy and do the math

https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient?oldid=1549180#Paladin_coefficients
https://tbcdb.com/?spell=31801

**Expected behavior**
Damage should scale by 3.4% of spell damage, not 2.2%

**Screenshots/videos**

this was taken with 5 points in 1H weapon specialization, hence why it's included in the calculations above.

![image](https://user-images.githubusercontent.com/4505074/109608543-09cf7100-7af8-11eb-8fa4-36e1383c9098.png)

**Additional context**

**Comment by blblblaz** [comment]
I did a quick test here:
![image](https://user-images.githubusercontent.com/53877162/109688333-d559c480-7b8c-11eb-9138-8967e0e4048c.png)

465 spell damage, no talents, 225 damage per tick with 5 stacks. Assuming 3.4% of spell damage scaling per stack it looks like this:
150 (base damage of SoV 5stack) + (465 * 0.17)  = 229.08. 

I've just checked and we are using the 3.4% per stack formula on our end, so this appears to be some sort of weird rounding issue, because notice that all numbers are "round" as in 170 or 225 in my case when it should be 229.08. If the formula was 2.2% per stack then my screenshot would look like something like this:

150 + (465 * 0.11) = 201.15 - so it's not like this

Confirming because it's a real issue regardless.

**Comment by kelno** [comment]
The way it works currently is that the spell damage is applied on the per stack value, I can match the values you get in last blaze test for example with:
added damage per stack = 465 * 0.034 = 15 (rounded down)
damage per tick per stack = 30 + 15 = 45
damage per tick with 5 stacks = 45 * 5 = 225

Now everything in the game currently works this way, and auras with stacks are especially affected. I can look into the way the rounding works but I'm not even sure it's incorrectly working atm.

**Comment by kelno** [comment]
Back on that last calculation, with more precise rounding it should do 229 damage instead. As I said, I'm not sure what's exactly blizzlike but I can make it so the rounding is more precise regardless.
Applied with next server update.
