### ISSUE TITLE
[core] [spell] Mind Numbing Poison and Curse of Tongues AFFECTS GCD (increases it)

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4761]
It shouldnt obviously... 

this is a stock mangos bug from 2008 btw

**Comment by Jerrythemagicdog** [comment]
It doesn't slow the GCD beyond the upper GCD cap (1.5s).
If there's any doubt that it should affect the GCD, here's a mage with spell haste meta gem proc and Icy Veins against Mind Numbing Poison:
https://youtu.be/IB7bUNWTlh4?t=201

We've tried to change this some time ago and weren't able to due to client limitations.
