### ISSUE TITLE
Dodge not being properly calculated 

### ISSUE THREAD

**Issue by westlakem** [ValorenWoW/sunstrider-core#4785]
**Describe the bug**
The amount of dodge a paladin receives is too low.

When calculating Dodge, Parry, and Block using values from this table:
https://wowwiki-archive.fandom.com/wiki/Combat_rating_system#From_Patch_2.1_through_Patch_3.1.3

Parry and block are within margin of error, but I'm calculating considerably more dodge.
Given the following data:
    agility = 108
    itemDodgeRating = 55 / 18.92  // 18.92 dodge rating per 1% dodge
    defenseRatingDodge = 263 / 59.25;  // 59.25 defense rating per 1% dodge
    defenseValueDodge = 20 / (59.25 / 2.36); // 20 defense rating from spec divided by (defense rating per 1% dodge / 2.36 defense rating per defense point)
    
Gives you a calculation of:
BaseDodge + (agility / 19.767) + itemDodge + defenseRatingDodge + defenseValueDodge
0.7 + (108 / 19.767) + 2.907 + 4.439 + 0.797 = 14.31% dodge

**Character name**
Nightbeast

**Expected behavior**
Dodge should be calculated to be within reason of 14.31%

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/4505074/110274468-e182bf00-7f9c-11eb-8dc4-bba703382f7d.png)
![image](https://user-images.githubusercontent.com/4505074/110274509-f9f2d980-7f9c-11eb-95b3-4c010b9f43b2.png)
![image](https://user-images.githubusercontent.com/4505074/110274731-7e455c80-7f9d-11eb-8715-a6196b019a35.png)

**Additional context**

**Comment by blblblaz** [comment]
I believe the issue here is that you're looking at a classic.wowhead table to calculate these things, I recommend looking at the 2008 WoW Wiki sections for these things as they are from retail TBC since these things work differently at lvl 60 and lvl 70, for example:  https://wowwiki-archive.fandom.com/wiki/Dodge?oldid=1432727

based on this you should be getting: 1% dodge chance per 25 Agility, 1% dodge chance per 18.91 Dodge Rating, and 5.28% from the 482 defense rating you have (vs level 70 mob). so it should look like this:

Agility: 108 / 25 = 4.32% dodge chance
Dodge Rating: 55 / 18.9231 = 2.9065% dodge chance
Defense Rating:  (482 - (70 × 5)) × 0.04 = 5.28% dodge chance
Base Paladin class dodge chance:  0.65%

so total is - 4.32 + 2.9065 + 5.28 + 0.65 = 13.1565% dodge chance, which gets rounded up to 13.16% when displayed on your character stats in game
