### ISSUE TITLE
[core] [spell] Clearcasting procs even when the invoker spell doesnt hit anything (AoE)

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4835]
![image](https://user-images.githubusercontent.com/1942409/111068132-c4cc1700-84c7-11eb-9129-ed2e807b8509.png)

it should be bound on a successful spell hit, currently procs even when you spam arcane explosion without hitting anything

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The proc rules were recently changed: https://github.com/SunstriderEmu/BugTracker/issues/3648
which is apparently supposed to mimic the Nature's Grace talent for Druids (not really confirmed but I can understand it in line with stuff below).
It would be cool to test on Classic, there's an argument from a Warmane dev saying that the tooltip is misleading in this case and that it should actually proc "on cast"
In any case from what information is available out there, the argument for it only procing "on cast" rather than "on hit" was because of AoE spells with cases like these:
https://wowwiki-archive.fandom.com/wiki/Arcane_Concentration?oldid=1432055
https://youtu.be/16l2kJPM0D0?t=87

At the same time there are other examples linked in those Warmane issues that contradict the "on cast" argument like: 
https://www.youtube.com/watch?v=IAoe3akMZUE&t=140s

Perhaps our understanding and implementation are incomplete here, there's a comment in the code from some time ago mentioning it for the previous workaround for AoE spells, before the Arcane Blast change:
> The proper way to do this would be to have the spell system actually calculate damage on launch

**Comment by ghost** [comment]
in the 2nd linked video (Noone3 at 02:25), it procced from mana gem, not icelance. (sorry necro)

**Comment by Evolvee** [comment]
on classic it procs from anything (if you event want to take that dogshit emulated game into account)
