### ISSUE TITLE
Quest "Shutting Down Manaforge Ara" can't get turned in

### ISSUE THREAD

**Issue by fntastXlol** [ValorenWoW/sunstrider-core#4893]
**Describe the bug**
I have done the quest "Shutting Down Manaforge Ara". The Manaforge has been shut down and i got the required crystal in my bag. The quest is marked as "completed in my questlog and the quest-giver even has the yellow mark on his head, but whatever i do, i cant proceed the dialog to turn in the quest, so please help :-)

On my Screenshot you can see the bugged NPC, the not working dialog and the quest item in my bag.

**Character name**
Andora

**relevant Links**
Item: https://www.wowhead.com/item=29411/ara-access-crystal
Quest: https://www.wowhead.com/quest=10365/shutting-down-manaforge-ara#comments
NPC: https://www.wowhead.com/npc=19468/spymaster-thalodien

**Expected behavior**
Please help me turning in this Quest or maybe give me the desired Reward :-)
expected reward from Quest: https://tbc.wowhead.com/item=30378/thalodiens-charm?bonus=6691

**Screenshots/videos**
![manaforge quest bug](https://user-images.githubusercontent.com/65029474/112738629-dc45de00-8f64-11eb-9f5a-d341d2c99625.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
You can't hand in the quest because you're not Friendly with the Scryers.
You've first picked the quest up (which is the Scryer version of the quest chain) and then most likely have done City of Light and chosen Aldor which resulted in you being Neutral with the Scryers, keeping in mind that Blood Elves start at a higher reputation with the Scryers.
If you're certain about going Aldor then I would suggest you first gain reputation with the Aldor and do the Aldor version of the quest instead (which is exactly the same, just starting from a different NPC nearby).
