### ISSUE TITLE
Cannot buy lvl 70 PVP weapons from vendor in Orgrimmar or Storm Wind

### ISSUE THREAD

**Issue by KlaesSoebert** [ValorenWoW/sunstrider-core#5009]
**Describe the bug**
Cannot buy lvl 70 PVP weapons from vendor in Orgrimmar or Storm Wind
 Sergeant Thunderhorn (npc) has no items. I use to buy weapons from him, but now it's all empty. Alot are complaining about it.-

**Character name**
Spiney and Rozza

**To Reproduce**
Just go to the refered npc and see all bags are empty. You can't buy anything at all. 

**Expected behavior**
There should be item to choose. It's all empty

**Screenshots/videos**
Adding screenshots/videos to help explain your problem is *extremely* appreciated.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/5489510/122771851-1ba37280-d2a7-11eb-8506-58a087c2eb5a.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next server update.
S2 weapons can be found on Sergeant Thunderhorn (Horde, the one in your screenshot) and Captain O'Neal (Alliance).
S3 weapons can be found on the nearby Armor vendors for a discounted Arena Points price (Lady Palanseer for Horde, Captain Dirgehammer for Alliance).
