### ISSUE TITLE
(CONFIRMED) Darkmoon Faire Not Running on Any Schedule and (SEEMINGLY) Cards Not Dropping Properly

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5045]
The Darkmoon Faire SHOULD be Running on a MONTHLY Schedule, on which it has not been for a while. Also SEEMINGLY, the Cards Have Not Been Dropping Properly, at Least According to Many Many Reports. 

Please Fix Both the Schedule, and (IF APPLICABLE) the Droprate for the Cards

Thank You

Draguli

**Comment by kelno** [comment]
Thanks for reporting. The faire runs the first monday of the month, next one is set to run on 2021/09/06 as expected. (In Mulgore)
If it doesn't you can notify me again here.

The cards have been reported here: https://github.com/SunstriderEmu/BugTracker/issues/4974
I do think they're just rare, I've been playing myself on Windrunner and didn't hear about it then, I think the issue is that with a low player count it's become very hard to collect them through the AH.
