### ISSUE TITLE
paladin dont get seal of crusader rank 1

### ISSUE THREAD

**Issue by taurme** [ValorenWoW/sunstrider-core#5084]
**Describe the bug**

i dont get my rank 1 seal of crusader
**Character name**Zuldrax

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
For now, you'll need to take a trip to one of these trainers to learn the spell:
Alliance:
https://tbc.wowhead.com/npc=925/brother-sammuel
https://tbc.wowhead.com/npc=926/bromos-grummner

Horde:
https://tbc.wowhead.com/npc=15280/jesthenis-sunstriker
https://tbc.wowhead.com/npc=16501/aurelon
