### ISSUE TITLE
Problem with my name

### ISSUE THREAD

**Issue by insidekot** [ValorenWoW/sunstrider-core#5098]

**Comment by insidekot** [comment]
good afternoon! I would like to play on your server but with my own name. my name (Inside) is level 63, same as 2 years ago. Could you free me my name so I can play with you with pleasure!?

**Comment by kelno** [comment]
Hello, to prove that account and characters is yours, can you connect on the account and create a character called "Insidekot"?

**Comment by insidekot** [comment]
Yes. I did as you requested.

**Comment by insidekot** [comment]
>Пятница, 11 марта 2022, 1:32 +04:00 от Kelno ***@***.***>:
> 
> 
>Hello, to prove that account and characters is yours, can you connect on it and create a character called "Insidekot"?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <SunstriderEmu/BugTracker/issues/5098/1064523590 @ github . com>
Yes. I did as you requested.
 
--
Warning170190 козлов
Отправлено из Почты  Mail.ru

**Comment by kelno** [comment]
Thanks. However I meant to create that character on the same account where the character "Inside" is. Is the character "Inside" currently on an account that you own?
Edit: since the character has been inactive for a long time we've made the name available. You can make a character called "Inside" now.
