### ISSUE TITLE
Spiritual Healing [Holy Priest]

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5126]
**Describe the bug**
Talent increase of healing is too low. It should increase all healing done by priest by 2% per point. 
When tested on Renew it did increase healing by about 1.7% per point and at 5/5 around 6.8% instead of 10% increase. 

For Lightwell it does not increase healing at all. To make sure I have waited till my Lightwell ended and casted new one (old one had 0/5 Spiritual Healing, new one casted at 5/5 Spiritual Healing). Their healing was the same. 

**To Reproduce**
1. Learn Spiritual Healing point by point. 
2. Observe healing increase each time.
3. Do maths to see it is too low. 

**Expected behavior**
Talent increases all healing from priest that has it by 2% per point. 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/42322589/166071375-09bcb3de-6b67-4665-b1ce-fea318755a5d.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Renew does the correct amount of healing with Spiritual Healing, I think you're doing the math incorrectly and expecting each tick to be increased by the talent % amount.
The way these increases work, unless specifically stated in the talent, is by increasing the overall amount of healing done by the spell (which is then divided by ticks the spell does).
https://wowwiki-archive.fandom.com/wiki/Spell_power#Over_time_spells

As to Lightwell, that's a pretty specific case - the talent is not affecting Lightwell's healing spell (48085). 
This could either be intentional on Blizzard's part or could be an oversight but until we can say with certainty which one it is then we're not going to act on it as there are a lot of similar cases (for example related to Penance).
