### ISSUE TITLE
Shaman - Earth Shield

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5297]
Earth Shield is currently dynamic and not snap-shotting bonus healing at the time of cast.

https://www.wowhead.com/tbc/spell=974/earth-shield#comments:id=3368290

https://youtu.be/HRcieR5kEWc?t=383

Will need to test for "A more powerful effect is already in place." message after fix when trying to replace earth shield with lower bonus healing earth shield.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
As for "A more powerful effect is already active." other shamans trying to override the stronger Earth Shield will get this message, the original caster will always be able to override it, that's consistent with our rule of always allowing to override your own spells.
