### ISSUE TITLE
Netherspite red beam not healing properly.

### ISSUE THREAD

**Issue by culjoboi** [ValorenWoW/sunstrider-core#5347]
**Describe the bug**
While fighting Netherspite, walking into the red beam does not heal you to full HP.

**To Reproduce**
1. Engage into the fight with Netherspite, and once the beams spawn stand in the red one.
2. Either after getting hit, or not, doesn't matter - walk outside of the red beam.
3. Make sure you are not at max HP anymore.
4. Walk back into the red beam and pay attention to your HP.

https://www.wowhead.com/tbc/npc=15689/netherspite

**Expected behavior**
Walking into the red beam should heal you to full HP.

**Additional context**
As seen in sources from the time of original TBC, TBC classic and other private servers, it should heal to full HP.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!

This is unfortunately caused by the 3.3.5a built-in client-side HP prediction.
Your HP is being set to full but the HP prediction doesn't display that correctly on your HP bar.
You can disable client-side HP prediction by running `/run SetCVar("predictedHealth", 0)`, perhaps we could add it to the array of options.
