### ISSUE TITLE
Travel Form not removing Dazed

### ISSUE THREAD

**Issue by Orishek** [ValorenWoW/sunstrider-core#5477]
_**Describe the bug**
A clear and concise description of what the bug is._

When druid enters into Travel Form, the act of shapeshifting should remove polymorph and movement impairing effects. Currently, travel form is doing everything correctly but one thing - it's not removing movement impairing debuff "Dazed" even though it should. Other movement impairing spells are removed correctly. 

_**Character name**
Character on which the issue occurred, if applicable._

Not related to character (Orisek if needed)

_**To Reproduce**
Steps to reproduce the behavior. The more details the better!_

1. Find a NPC who Dazes players (Shadowmoon Slayer ID 22082 for example)
2. Get Dazed
3. Shapeshift into Travel Form
4. See Dazed not removed from player

_Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page._ 

Spell: https://tbc.wowhead.com/spell=1604/dazed

__**Expected behavior**_
A clear and concise description of what you expected to happen._

Dazed should be removed as it's movement impairing effect and it used to work correctly on official TBC realms.

**Comment by kelno** [comment]
The current behavior seems correct, from my research being able to remove it seems to be unintended behavior from tbc classic (maybe fixed since then idk).

https://wowpedia.fandom.com/wiki/Daze "While it slows movement speed, creature daze is not considered a movement impairing effect"
https://www.reddit.com/r/wow/comments/97o7ao/why_does_shapeshifting_as_a_druid_not_remove_the/ 
https://www.reddit.com/r/classicwow/comments/px75yv/bug_druids_are_suddenly_able_to_shift_out_of/
