### ISSUE TITLE
Help with Error

### ISSUE THREAD

**Issue by Opa4ku** [ValorenWoW/sunstrider-core#5539]
**Describe the bug**

**Character name**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. I can't play on my character. In loading screen i see error message
2. Name Vegas
3. Fix this pls
![Error](https://user-images.githubusercontent.com/75784358/162726382-c727a243-44f8-4534-bec7-a43c08e924e5.jpg)

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Additional context**

**Comment by GM-Morsrael** [comment]
Hey, please use our technical issues ticket on our discord for issues like this, or make a ticket on an alt/dm a GM. I've teleported you to Shattrath which will allow you to log in, but you'll need to reinstall the game from our website to permanently fix this issue.

"We had an issue with the first client on our website containing a broken file, which in some cases makes players crash and not be able to reconnect to that specific character without Game Master’s assistance. The issue was fixed some time ago but redownloading the client is needed. https://sunstrider.gg/getstarted"

**Comment by Opa4ku** [comment]
Im client and its work well. Tnx 4 help
