### ISSUE TITLE
Shaman's elemental shield doesn't proc from AoE spells.

### ISSUE THREAD

**Issue by weaver-0f-fate** [ValorenWoW/sunstrider-core#5546]
**Describe the bug**
Shaman's elemental shield doesn't proc from AoE spells.

**Character name**
Weavelol

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. apply any elemental shield on yourself (Lightning shield, water shield, earth shield)
2. get damage from aoe abbility (not sure if it is all aoe abilities or just some of them)
3. shield dont proc

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Spell: https://tbc.wowhead.com/spell=33736/water-shield
Spell: https://tbc.wowhead.com/spell=25472/lightning-shield

**Expected behavior**
Description is saying: 'When a spell, melee or ranged attack hits the caster, ...' - meaning AoE spell should also trigger the effect.

**Additional context**
Adding some twitch clips when you can see my lightning shield doesn't proc from whirlwind on Lurker and Pounding on Void Reaver:
https://clips.twitch.tv/CourageousCrypticStorkBleedPurple-ofe1eUt0xvdXZWdM
https://clips.twitch.tv/AgitatedAlluringSandstormFailFish-XueDCkkOxEl0YvNe

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Doesn't seem to be the case at least on Classic TBC:

1. Lightning Shield not procing from Void Reaver's Pounding: 
https://www.youtube.com/watch?v=VfLj1K6nV4s&t=445s
2. Water Shield not procing from Lurker's Whirl (only procs from Geyser):
https://youtu.be/DL5ZhDhXtEM?t=8

If you'd like to provide examples that prove otherwise, like footage from retail TBC, please post them here.
