### ISSUE TITLE
Damage over time does not procc clearcast

### ISSUE THREAD

**Issue by Neverik90** [ValorenWoW/sunstrider-core#5562]
The mage talent Arcane Concentration can only proc at the start of casting a spell when it should proc after any dmg spell hits the target. It should e.g. be possible to proc this with tics of Blizzard or Flamestrike.

**Comment by dedestus** [comment]
this report is not correct or do you have any sources proving your statement? on wowhead comments and blizzard forums i am only able to find the following information on arcane concentration / clearcasting procs gained from the talent:


https://www.wowhead.com/classic/spell=12577/arcane-concentration#comments
Is this affected by any AOE afflicted enemy hit? In that case, if the Mage is surrounded by about 10 enemies, it would mean that he/she'll be in clearcast state almost the whole time, and can AOE spam almost for free...

(Patch 2.0.1)Subject: "Not affected by AOE"
No, multiple hits on multiple targets don't increase the chance for it to proc. One damage spell, one chance to proc. Channeled spells (think arcane missiles) can have multiple "misses" and/or multiple hits, but if any of the volley hits, then the entire spell has a 10% chance to proc. Not once per hit, which would give AM a 40.95% chance to proc clearcasting. Alas.

and

https://us.forums.blizzard.com/en/wow/t/what-triggers-clearcasting/586689/7

https://www.wowhead.com/tbc/spell=12577/arcane-concentration#comments

because of what you suggest would result in 100% uptime of clearcast and never being able to oom again as a mage

**Comment by Neverik90** [comment]
You are right but i am not saying that the chance of proccing clearcast should be affected by AOE or the number of enemies hit.
But when you cast Blizzard it hits like 7 or 8 times and for each of this times you have a 10% chance of proccing clearcast.
It doesnt matter if you hit 1 enemy or 20 with it.
The same applies for ticks of the Flamestrike damage over time or the Ignite talent in the fire tree.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/5232
