### ISSUE TITLE
When the player robot system is started, the server will burst immediately after the completion of the server.

### ISSUE THREAD

**Issue by woiwoz** [ValorenWoW/sunstrider-core#7]
When the player robot system is started, the server will burst immediately after the completion of the server.

os: windows7 x64

**Comment by kelno** [comment]
Thanks.
PlayerBot is currently only partially used (by the Testing system) and most of it is still probably buggy at this time. I don't plan on supporting it anytime soon, except if you find any errors are caused by the tests.
That being said, I you want to play with it you may want to spawn individuals bots as described here:
http://ike3.github.io/mangosbot-docs/doc/playerbot/QuickStart.html
